Xavier Perez Gonzalez - - ANR 386264
===============

Analysis of salaries gap in Regions in Spain
===============

## Final Assignment  - Applied Economics 1

### Question: 
Are there regional differences in salaries in Spain?


#### Motivation:
The economic differences across regions in Spain are wide. More specifically, the salaries across Spain regions vary. For example, in industrial regions, such as Basque country or Catalonia, salaries are close to the average of UE. And in less developed regions like Andalusia or Extremadura, the salaries are lower. Other touristic regions such as Canary Islands or Balearic Islands have some specifics characteristics in their labour market that make them difficult to classify. In this context, the effect of the education on salary is an interesting topic to discuss.

#### Data:
The data of this study is retrieved from the four-yearly [Wage Structure Survey of 2010](http://www.ine.es/dyngs/INEbase/en/operacion.htm?c=Estadistica_C&cid=1254736177025&menu=resultados&secc=1254736195110&idp=1254735976596). The quality of the data is guaranteed as includes 28,500 establishments and 220,000 workers. Although, the data regard the workers of the Autonomous cities of Ceuta and Melilla can be statistically insignificantly as both cities have a population of 85,000 approximately.
The INE (Spanish Statistical Office) offers a microdata file detailed with the characteristics of the worker, the establishment, and the contract of the worker. The microdata is somewhat capped to accomplish confidentiality requirements. Another constraint is the absence of data of agricultural employment.


#### Method:
To find the contribution of an extra year of the salary two equations are been designed based on [Pastor et al (2007)](http://www.ivie.es/es/productos/85-el-rendimiento-del-capital-humano-en-espana.php). The first equation is the basic equation of wage without regions variable.The equation only contains years of education, years of experience, years of experience to the second power in order to capture the concave slop of experience and the gender, .

(1) $$\ Ln (Salary/hour) = \beta_1 educyears+ \beta_2 expyears+ \beta_3 expyears^2+ \beta_4 woman + \epsilon_i \\$$

Where $educyears$ is the number of years of education of the workers, $expyears$ is the number of years of experience of the worker, $expyears^2$ is the number of years of experience of the workers raised to the second power, $woman$ is a gender dichotomous variable of the worker and ε is the random error term.

(2)   $$\ Ln(Salary/hour) =  \beta_1 educyears+ \beta_2 expyears+ \beta_3 expyears2+ \beta_4 woman+ \beta_5 fulltime+  \beta_6 permanentcontract + \beta_7 Energysector+ \beta_8 Manufacturing+ \beta_9 Office+ \beta_{10} Retailing+ \beta_{11} Transport+ \beta_{12} Hospitality+ \beta_{13} Information+ \beta_{14} Finance+ \beta_{15} Scientific+ \beta_{16} Outofmarketservices + \beta_{17} Arts+ \beta_{18} Otherservices + \epsilon_i \\$$

Where $fulltime$ is dichotomous variable of type of working day and $permanentcontract$ is dichotomous variable of type of length of the contract. The other variables are the sector of the establishment of the worker. The construction sector is being left out as reference.

## Importing Libraries

In [9]:

import matplotlib.pyplot as plt
from astropy.table import Table, Column
from pandas.stats.plm import * 
import pandas as pd
import statsmodels.formula.api as sm

information=pd.DataFrame.from_csv('/Users/Xavi/Documents/Xavi/Applied Economics/Final Assignment/xavi_data.csv')
data.head()

,ORDENTRA,REG,SECC,ESTRATO,CONTROL,MERCADO,REGULACION,SEXO,ANONAC,NACI,...,madrid,murcia,navarra,pvasco,rioja,exp2,expe2,secenergetico,inmofin,serviciosfueradelmercado
ORDENCCC,,,,,,,,,,,,,,,,,,,,,
1000027.0,1,16,B0,1,2,1,2,1,1952,1,...,0,0,0,1,0,2116,2116,1,0,0
1000027.0,2,16,B0,1,2,1,2,1,1957,1,...,0,0,0,1,0,1681,1681,1,0,0
1000028.0,1,16,C0,2,2,3,3,1,1950,1,...,0,0,0,1,0,1369,1369,0,0,0
1000028.0,2,16,C0,2,2,3,3,6,1956,1,...,0,0,0,1,0,1296,1296,0,0,0
1000028.0,3,16,C0,2,2,3,3,1,1950,1,...,0,0,0,1,0,2304,2304,0,0,0


Table 1 shows the summary of all the variables.

#### Table 1

In [11]:
information.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ORDENTRA,174350.0,8.166183,6.816664,1.0000,3.000000,6.000000,13.000000,50.0000
REG,174350.0,9.113679,4.523674,1.0000,6.000000,9.000000,13.000000,18.0000
ESTRATO,174350.0,3.580614,1.530800,1.0000,2.000000,4.000000,5.000000,5.0000
CONTROL,174350.0,1.864302,0.342469,1.0000,2.000000,2.000000,2.000000,2.0000
MERCADO,174350.0,1.882392,0.934500,1.0000,1.000000,2.000000,2.000000,4.0000
REGULACION,174350.0,2.026355,0.787836,1.0000,1.000000,2.000000,3.000000,3.0000
SEXO,174350.0,3.119644,2.470904,1.0000,1.000000,1.000000,6.000000,6.0000
ANONAC,174350.0,1969.687927,10.533206,1930.0000,1962.000000,1971.000000,1978.000000,1994.0000
NACI,174350.0,1.150622,0.647556,1.0000,1.000000,1.000000,1.000000,5.0000
CNO2,174350.0,53.520786,24.705854,11.0000,34.000000,45.000000,75.000000,98.0000
RESPONSA,174350.0,0.189590,0.391978,0.0000,0.000000,0.000000,0.000000,1.0000
CESTUDIO,174350.0,34.448311,15.900132,11.0000,23.000000,32.000000,54.000000,80.0000
ANOANTI,174350.0,8.815681,9.646994,0.0000,2.000000,5.000000,12.000000,56.0000
MESANTI,174350.0,5.145380,3.488719,0.0000,2.000000,5.000000,8.000000,11.0000
TIPOJOR,174350.0,1.162851,0.369230,1.0000,1.000000,1.000000,1.000000,2.0000
TIPOCON,174350.0,1.221898,0.415524,1.0000,1.000000,1.000000,1.000000,2.0000
FIJODISM,174350.0,0.148397,1.146516,0.0000,0.000000,0.000000,0.000000,11.0000
FIJODISD,174350.0,0.158807,1.737869,0.0000,0.000000,0.000000,0.000000,29.0000
VAL,174350.0,9.048122,11.593061,0.0000,0.000000,0.000000,22.000000,86.0000
VAN,174350.0,17.678836,14.951904,0.0000,0.000000,30.000000,30.000000,99.0000
PUENTES,174350.0,1.564703,3.156233,0.0000,0.000000,0.000000,2.000000,60.0000
JAP,174350.0,1604.368271,354.332044,9.0000,1620.000000,1744.000000,1776.000000,2250.0000
JSP1,174350.0,36.034706,7.982094,0.0000,36.000000,40.000000,40.000000,49.0000
JSP2,174350.0,5.111443,12.546944,0.0000,0.000000,0.000000,0.000000,59.0000
HEXTRA,174350.0,0.990141,6.455540,0.0000,0.000000,0.000000,0.000000,113.0000
DRELABM,174350.0,30.984927,0.530907,2.0000,31.000000,31.000000,31.000000,31.0000
SIESPM1,174350.0,5.643390,1.286814,1.0000,6.000000,6.000000,6.000000,6.0000
DSIESPM1,174350.0,1.215188,5.381447,0.0000,0.000000,0.000000,0.000000,31.0000
SIESPM2,174350.0,5.971924,0.373619,1.0000,6.000000,6.000000,6.000000,6.0000
DSIESPM2,174350.0,0.014098,0.314796,0.0000,0.000000,0.000000,0.000000,30.0000
...,...,...,...,...,...,...,...,...
escolaridad,174350.0,11.738015,3.620007,0.0000,10.000000,12.000000,15.000000,18.0000
expe,174350.0,22.574058,11.573498,-4.0000,13.000000,21.000000,31.000000,66.0000
jap,174350.0,1604.368271,354.332044,9.0000,1620.000000,1744.000000,1776.000000,2250.0000
salario_hombre,174350.0,7.617738,10.362618,0.0000,0.000000,6.718419,11.498977,423.9575
salario_mujer,174350.0,4.475448,7.099162,0.0000,0.000000,0.000000,7.724111,775.0192
prueba,174350.0,3.142290,15.032230,-775.0192,-7.724111,6.718419,11.498977,423.9575
SALTOTAL,174350.0,1946.330259,1519.555374,8.8200,1143.510000,1588.700000,2351.597500,70350.5700
saltotal,174350.0,1946.330259,1519.555374,8.8200,1143.510000,1588.700000,2351.597500,70350.5700
cat,174350.0,0.176169,0.380965,0.0000,0.000000,0.000000,0.000000,1.0000
asturias,174350.0,0.031494,0.174649,0.0000,0.000000,0.000000,0.000000,1.0000
andalucia,174350.0,0.099816,0.299756,0.0000,0.000000,0.000000,0.000000,1.0000
aragon,174350.0,0.038709,0.192902,0.0000,0.000000,0.000000,0.000000,1.0000
balears,174350.0,0.028087,0.165222,0.0000,0.000000,0.000000,0.000000,1.0000
canarias,174350.0,0.040172,0.196363,0.0000,0.000000,0.000000,0.000000,1.0000
cantabria,174350.0,0.022237,0.147453,0.0000,0.000000,0.000000,0.000000,1.0000
cyl,174350.0,0.049211,0.216310,0.0000,0.000000,0.000000,0.000000,1.0000
clm,174350.0,0.040224,0.196484,0.0000,0.000000,0.000000,0.000000,1.0000
cvalenciana,174350.0,0.081962,0.274307,0.0000,0.000000,0.000000,0.000000,1.0000
extremadura,174350.0,0.021107,0.143741,0.0000,0.000000,0.000000,0.000000,1.0000
galicia,174350.0,0.054018,0.226053,0.0000,0.000000,0.000000,0.000000,1.0000
madrid,174350.0,0.186418,0.389445,0.0000,0.000000,0.000000,0.000000,1.0000
murcia,174350.0,0.030726,0.172574,0.0000,0.000000,0.000000,0.000000,1.0000
navarra,174350.0,0.025139,0.156548,0.0000,0.000000,0.000000,0.000000,1.0000
pvasco,174350.0,0.056742,0.231350,0.0000,0.000000,0.000000,0.000000,1.0000
rioja,174350.0,0.014855,0.120973,0.0000,0.000000,0.000000,0.000000,1.0000
exp2,174350.0,643.533186,588.057878,0.0000,169.000000,441.000000,961.000000,4356.0000
expe2,174350.0,643.533186,588.057878,0.0000,169.000000,441.000000,961.000000,4356.0000
secenergetico,174350.0,0.022231,0.147435,0.0000,0.000000,0.000000,0.000000,1.0000
inmofin,174350.0,0.045781,0.209011,0.0000,0.000000,0.000000,0.000000,1.0000
serviciosfueradelmercado,174350.0,0.149286,0.356371,0.0000,0.000000,0.000000,0.000000,1.0000


Table 2 shows the results of the first regression.

#### Table 2

In [16]:
result = sm.ols('log_salariohora ~ escolaridad + expe + exp2 + mujer + cat + pvasco + andalucia + extremadura + canarias + balears', data=information).fit()
print result.summary()

                            OLS Regression Results
==============================================================================
Dep. Variable:        log_salariohora   R-squared:                       0.287
Model:                            OLS   Adj. R-squared:                  0.287
Method:                 Least Squares   F-statistic:                     7027.
Date:                Wed, 18 Jan 2017   Prob (F-statistic):               0.00
Time:                        21:35:21   Log-Likelihood:                -98835.
No. Observations:              174350   AIC:                         1.977e+05
Df Residuals:                  174339   BIC:                         1.978e+05
Df Model:                          10
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [95.0% Conf. Int.]
-------------------------------------------------------------------------------
Intercept       1.1692      0.006    190.843      0.000         1.157     1.181
escolaridad     0.0726      0.000    230.958      0.000         0.072     0.073
expe            0.0224      0.000     63.375      0.000         0.022     0.023
exp2           -0.0002   6.94e-06    -24.482      0.000        -0.000    -0.000
mujer          -0.2123      0.002   -101.924      0.000        -0.216    -0.208
cat             0.0859      0.003     30.853      0.000         0.080     0.091
pvasco          0.1166      0.004     25.920      0.000         0.108     0.125
andalucia      -0.0111      0.004     -3.176      0.001        -0.018    -0.004
extremadura    -0.1352      0.007    -18.872      0.000        -0.149    -0.121
canarias       -0.0980      0.005    -18.582      0.000        -0.108    -0.088
balears         0.0140      0.006      2.244      0.025         0.002     0.026
==============================================================================
Omnibus:                    25155.722   Durbin-Watson:                   0.981
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            67176.590
Skew:                           0.800   Prob(JB):                         0.00
Kurtosis:                       5.586   Cond. No.                     6.22e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.22e+03. This might indicate that there are
strong multicollinearity or other numerical problems.


And Table 3 shows the results of regression 2:

#### Table 3

In [19]:
result = sm.ols('log_salariohora ~ escolaridad + expe + exp2 + mujer + +indefinido + extractivas + manufacturas + energia + agua + comercio + transporte + hosteleria + informacion + finanzas + tcompleto + ciencias + educacion + sanidad + artisticas + otros_servicios + cat + pvasco + andalucia + extremadura + canarias + balears', data=information).fit()
print result.summary()

                            OLS Regression Results
==============================================================================
Dep. Variable:        log_salariohora   R-squared:                       0.335
Model:                            OLS   Adj. R-squared:                  0.334
Method:                 Least Squares   F-statistic:                     3371.
Date:                Wed, 18 Jan 2017   Prob (F-statistic):               0.00
Time:                        21:44:41   Log-Likelihood:                -92852.
No. Observations:              174350   AIC:                         1.858e+05
Df Residuals:                  174323   BIC:                         1.860e+05
Df Model:                          26
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [95.0% Conf. Int.]
-----------------------------------------------------------------------------------
Intercept           1.1105      0.007    170.564      0.000         1.098     1.123
escolaridad         0.0638      0.000    195.563      0.000         0.063     0.064
expe                0.0177      0.000     50.405      0.000         0.017     0.018
exp2               -0.0001   6.84e-06    -15.252      0.000        -0.000 -9.09e-05
mujer              -0.2011      0.002    -93.310      0.000        -0.205    -0.197
indefinido          0.0802      0.003     31.210      0.000         0.075     0.085
extractivas         0.0822      0.015      5.533      0.000         0.053     0.111
manufacturas        0.0695      0.003     24.020      0.000         0.064     0.075
energia             0.6954      0.024     29.320      0.000         0.649     0.742
agua                0.1179      0.008     14.494      0.000         0.102     0.134
comercio           -0.0081      0.004     -2.006      0.045        -0.016    -0.000
transporte          0.1173      0.005     23.407      0.000         0.107     0.127
hosteleria          0.0101      0.006      1.664      0.096        -0.002     0.022
informacion         0.1083      0.005     21.826      0.000         0.099     0.118
finanzas            0.3571      0.005     66.001      0.000         0.346     0.368
tcompleto           0.1051      0.003     36.521      0.000         0.099     0.111
ciencias            0.0167      0.004      3.788      0.000         0.008     0.025
educacion           0.1700      0.007     25.184      0.000         0.157     0.183
sanidad             0.2163      0.004     51.494      0.000         0.208     0.225
artisticas         -0.0360      0.008     -4.725      0.000        -0.051    -0.021
otros_servicios    -0.0966      0.007    -13.362      0.000        -0.111    -0.082
cat                 0.0824      0.003     30.578      0.000         0.077     0.088
pvasco              0.1246      0.004     28.623      0.000         0.116     0.133
andalucia          -0.0036      0.003     -1.068      0.285        -0.010     0.003
extremadura        -0.1412      0.007    -20.374      0.000        -0.155    -0.128
canarias           -0.0911      0.005    -17.755      0.000        -0.101    -0.081
balears             0.0288      0.006      4.739      0.000         0.017     0.041
==============================================================================
Omnibus:                    26253.786   Durbin-Watson:                   1.027
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            74551.170
Skew:                           0.813   Prob(JB):                         0.00
Kurtosis:                       5.761   Cond. No.                     2.10e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.1e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

## Conclusion

As observed from regression 1 and from regression 2 using more control variables, the regions with more industry ('cat' for Catalonia and 'pvasco' for Basque Contry) have higher salaries compared to the rest of Spain. Also, we can see that from the touristic region, only 'balears' (Balearic Islands) has higher salaries while the Canarian Islands ('canarias')
. Finally, the less developed regions have lower salaries as expected ('andalucia' for Andalucia' and 'extremadura' for Extremadura).